/*
 * 	calendar.h
 *
 *	defines and constants for the 1962 Roman Catholic Litugical Calendar
 */

#ifndef c_calendar_h
#define c_calendar_h

#define     SEASON_GREEN        "#C3FDB8"
#define     SEASON_PURPLE       "#E0B0FF"
#define     SEASON_YELLOW       "#FFFFC2"
#define     SEASON_ROSE         "#FAAFBA"
#define 	SEASON_GOLD			"#FFF380"

/*
 * this enumeration coincides with the return value in determinedaycode
 */
typedef enum
{
	sun = 0,
	mon = 1,
	tue = 2,
	wed = 3,
	thu = 4,
	fri = 5,
	sat = 6
} dayofweek_t;

typedef enum
{
	january = 1,
	february,
	march,
	april,
	may,
	june,
	july,
	august,
	september,
	october,
	november,
	december,
} month_t;

typedef enum
 {
     class_i = 1,
     class_ii = 2,
     class_iii = 3,
     class_iv = 4,
 } class_t;

typedef enum
{
	sunday,
	feria,
	vigil,
	feast,
	octave,
} type_t;

typedef enum
{
	advent,
	christmas,
	epiphany,
	lent,
	easter,
	pentecost,
} season_t;

typedef struct
{
	int		day;
	type_t	type;
	class_t	class;
	char*	name;
	char*	note;
	char*	devotion;
} day_t;

typedef enum
{
	none = 0,
	fast,
	abstain,
	partial,
} fast_t;

typedef enum
{

	/* Feasts of our Lord */
	ChristtheKing = 1,
	MostHolyName,
	BaptismLord,
	MostPreciousBlood,
	Transfiguration,
	VigiloftheAssumption,
	Assumption,

    Advent_1,
    Advent_2,
    Advent_3,
    Advent_4,
    Advent_WedEmber,
    Advent_FriEmber,
    Advent_SatEmber,
	VigilChristmas,
    Christmas,
	Christmas_Day5,
	Christmas_Day6,
	Christmas_Day7,
    Rogation,
    RogationMon,
    RogationTue,
    RogationWed,
    Septuagesima,
    Sexagesima,
    Quinquagesima,
    AshWednesday,
    Lent_1,
    Lent_WedEmber,
    Lent_FriEmber,
    Lent_SatEmber,
    Lent_2,
    Lent_3,
    Lent_4,
    PassionSunday,
    PalmSunday,
	HolyMonday,
	HolyTuesday,
	SpyWednesday,
    MaundyThursday,
    GoodFriday,
    HolySaturday,
    Easter,
	Easter_Mon,
	Easter_Tue,
	Easter_Wed,
	Easter_Thur,
	Easter_Fri,
	Easter_Sat,
    Easter_1,
    Easter_2,
    Easter_3,
    Easter_4,
    Easter_5,
    Easter_6,
    Ascension,
    Ascension_1,
    Epiphany,
    Epiphany_1,
    Epiphany_2,
    Epiphany_3,
    Epiphany_4,
    Epiphany_5,
    Epiphany_6,
    Trinity,
    ExaltationofHolyCross,
	VigilPentecost,
    Pentecost_1,
    Pentecost_Mon,
    Pentecost_Tue,
    Whit_WedEmber,
    Pentecost_Thur,
    Whit_FriEmber,
    Whit_SatEmber,
    Pentecost_2,
    Pentecost_3,
    Pentecost_4,
    Pentecost_5,
    Pentecost_6,
    Pentecost_7,
    Pentecost_8,
    Pentecost_9,
    Pentecost_10,
    Pentecost_11,
    Pentecost_12,
    Pentecost_13,
    Pentecost_14,
    Pentecost_15,
    Pentecost_16,
    Pentecost_17,
    Pentecost_18,
    Pentecost_19,
    Pentecost_20,
    Pentecost_21,
    Pentecost_22,
    Pentecost_23,
    Pentecost_24,
    Pentecost_25,
    Pentecost_26,
    Pentecost_27,
    Pentecost_Last,


	/* Feasts of Our Lady */
	PurificationofVirgin,
	OurLadyofLourdes,
	AnnunciationofOurLady,
	OurLadyVirginandQueen,
	VisitationofOurLady,
	ImmaculateHeartofMary,
	NativityoftheBlessedVirginMary,
	OurLadyoftheRosary,
	MotherhoodoftheBlessedVirgin,
	PresentationoftheBlessedVirgin,
	ImmaculateConception,

	/* Feasts of Angels */
	StGabrielArchangel,
	StRaphael,
	StMichael,

	/* Feasts of St John the Baptist, St Peter, St Paul ... */
	ConversionStPaul,
	StTimothy,
	StJoseph,
	StMark,
	SSPhilipJames,
	NativityofStJohnBaptist,
	SSJohnandPaul,
	SSPeterandPaul,
	CommStPaul,
	StJamestheGreater,
	BeheadingofStJohn,
	SSSimonandJude,
	StThomas,
	StStephen,
	StJohn,

	/* Feasts of Martyrs */

    Michaelmas_WedEmber,
    Michaelmas_FriEmber,
    Michaelmas_SatEmber,
	OctaveNativity,
	StHyginus,
	StHillary,
	StPaulHermit,
	StMarcellusI,
	StAntony,
	SSFabianSebastion,
	StAgnes,
	SSVincentAnastasius,
	StRaymondPenafort,
	StJohnChrysostom,
	StPeterNolasco,
	StFrancisdeSales,
	StMartina,
	StJohnBosco,
	StIgnatiusofAntioch,
	StAndrewCorsini,
	StAgatha,
	StTitus,
	StRomuald,
	StJohnofMatha,
	StCyrilofAlexandria,
	StScholastica,
	HolyFoundersServites,
	ChairStPeter,
	StPeterDamian,
	StMatthias,
	StGabrielSorrows,
	StCasimer,
	SSPerpetuaFelicitas,
	StThomasAquinas,
	StJohnofGod,
	StFrancisofRome,
	FortyMartyrsofSebaste,
	GregorytheGreat,
	StPatrick,
	StCyril,
	StBenedict,
	StJohnDamascene,
	StJohnCapistran,
	StFrancisofPaul,
	StIsidore,
	StVincentFerror,
	StLeoI,
	StHermenegild,
	StJustin,
	StAnselm,
	SSSoterCaius,
	StFidelis,
	SSCletusMarcellinus,
	StPeterCanisius,
	StPauloftheCross,
	StPeterofVerona,
	StCatherineofSiena,
	StJosephtheWorker,
	StAthanasius,
	StMonica,
	StPiusV,
	StStanislaus,
	StGregoryNazianzen,
	StAntoninius,
	SSNerusAchilleus,
	StRobertBellarmine,
	StJohnBaptiste,
	StUbaldus,
	StPascalBaylon,
	StVenantius,
	StPeterCelestine,
	StBernadineofSiena,
	StGregory,
	StPhilipNeri,
	StBedetheVenerable,
	StAugustineofCanterbury,
	StMaryMagdelenofPazzi,
	StAngelaMerici,
	StFrancisCaracciolo,
	StBoniface,
	StNorbert,
	StMargaret,
	StBarnabas,
	StJohnofSanFacundo,
	StAnthonyofPadua,
	StBasiltheGreat,
	StGregoryBarbarigo,
	StEphram,
	StJulianaFalconieri,
	StAloyiusGonzaga,
	StPaulinus,
	StWilliam,
	StLeoII,
	StAnthonyMariaZaccaria,
	SSCyrilMethodius,
	StElizabeth,
	SevenHolyBrothers,
	StJohnGualbert,
	StAnacletus,
	StBonaventure,
	StHenry,
	StCamillusdeLellis,
	StVincentdePaul,
	StJeromeEmilian,
	StLawrenceBrindisi,
	StMaryMagdalen,
	StApollinaris,
	StAnne,
	StNazariusCelsus,
	StMartha,
	StIgnatiusofLoyola,				
	StAlphonsusLigouri,
	StDominic,
	OurLadyoftheSnow,
	StCajetan,
	StJohnVianney,
	VigilofStLawrence,
	StLawrence,
	StClare,
	StJoachim,
	StHyacinth,
	StJohnEudes,
	StBernard,
	StJaneFrancesFremoitdeChantel,
	StPhilipBenizi,
	StBartholomew,
	StLouisIX,
	StJosephCalasanctius,
	StAugustine,
	StRoseofLima,
	StRaymondNonnatus,
	StStephenKingofHungary,
	StPiusX,
	StLawrenceJustinian,
	StNicholasofTolentino,
	MostHolyNameofMary,
	ExaltationoftheHolyCross,
	SevenSorrows,
	StCornelius,
	StJosephofCupertino,
	StJanarius,
	StMatthew,
	StThomasofVillanova,
	StLinus,
	SSCosmasDamian,
	StWencelaus,
	StJerome,
	HolyGuardianAngels,
	StTeresaoftheChild,
	StFrancisofAssisi,
	StBruno,
	StBridgetofSweden,
	StJohnLeonardi,
	StFrancisBorgia,
	StEdward,
	StCallistasI,
	StTeresaofAvila,
	StHedwig,
	StMargaretMAlacoque,
	StLuke,
	StPeterofAlacantra,
	StJohnCantius,
	StAnthonyMaryClaret,
	AllSaints,
	AllSouls,
	StCharlesBorromeo,
	DedicationoftheBasilicaofOurSavior,
	StAndrewAvellino,
	StMartin,
	StMartinI,	
	StDidicus,
	StJosephat,
	StAlberttheGreat,
	StGertrude,
	StGregorytheWonderworker,
	DedicationoftheBasilicasofSSPeterPaul,
	StElizabethofHungary,
	StFelixofValois,
	StCecilia,
	StClementI,
	StJohnoftheCross,
	StCatherineofAlexandria,
	StSylvester,
	StAndrew,
	StBibiana,
	StFrancisXavier,
	StPeterChrysolgus,
	StNicholas,
	StAmbrose,
	StDamasusI,
	StLucy,
	StEusebius,
	HolyInnocents,
} liturgicalday_t;

#endif
